import jsPDF from 'jspdf';

export const exportToPDF = (chunks, finalPercentage) => {
  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.setTextColor(102, 126, 234);
  doc.text('Plagiarism Check Report', 105, 20, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 105, 28, { align: 'center' });

  doc.setFillColor(102, 126, 234);
  doc.rect(20, 35, 170, 25, 'F');
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text('Final Plagiarism Percentage', 105, 45, { align: 'center' });
  doc.setFontSize(24);
  doc.text(`${finalPercentage.toFixed(2)}%`, 105, 55, { align: 'center' });

  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Chunk Details:', 20, 75);
  
  let yPos = 85;
  const totalWords = chunks.reduce((sum, c) => sum + c.wordCount, 0);
  
  doc.setFontSize(10);
  chunks.forEach((chunk, index) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setTextColor(0, 0, 0);
    doc.text(`Chunk ${index + 1}:`, 25, yPos);
    doc.text(`${chunk.wordCount} words`, 60, yPos);
    doc.text(`${chunk.plagiarismPercentage}%`, 110, yPos);

    const barWidth = 60;
    const fillWidth = (chunk.plagiarismPercentage / 100) * barWidth;
    doc.setDrawColor(200, 200, 200);
    doc.rect(130, yPos - 3, barWidth, 5);

    if (chunk.plagiarismPercentage < 20) {
      doc.setFillColor(52, 168, 83);
    } else if (chunk.plagiarismPercentage < 50) {
      doc.setFillColor(255, 193, 7);
    } else {
      doc.setFillColor(211, 47, 47);
    }
    doc.rect(130, yPos - 3, fillWidth, 5, 'F');
    
    yPos += 10;
  });
  
  yPos += 10;
  if (yPos > 270) {
    doc.addPage();
    yPos = 20;
  }
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Total Words: ${totalWords}`, 20, yPos);
  doc.text(`Total Chunks: ${chunks.length}`, 20, yPos + 5);

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Plagiarism Split Checker', 105, 285, { align: 'center' });

  doc.save(`plagiarism-report-${Date.now()}.pdf`);
};
