export const shareResults = async (finalPercentage, chunks) => {
  const shareText = generateShareText(finalPercentage, chunks);

  if (navigator.share) {
    try {
      await navigator.share({
        title: 'Plagiarism Check Results',
        text: shareText,
      });
      return true;
    } catch (err) {
      if (err.name !== 'AbortError') {
        console.error('Share failed:', err);
      }
      return copyToClipboard(shareText);
    }
  } else {
    return copyToClipboard(shareText);
  }
};

const copyToClipboard = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Clipboard copy failed:', err);
    return false;
  }
};

const generateShareText = (finalPercentage, chunks) => {
  const totalWords = chunks.reduce((sum, c) => sum + c.wordCount, 0);

  let text = `Plagiarism Check Results\n\n`;
  text += `Final Plagiarism: ${finalPercentage.toFixed(2)}%\n`;
  text += `Total Words: ${totalWords}\n`;
  text += `Chunks Analyzed: ${chunks.length}\n\n`;
  text += `Breakdown:\n`;
  
  chunks.forEach((chunk, index) => {
    text += `  Chunk ${index + 1}: ${chunk.plagiarismPercentage}% (${chunk.wordCount} words)\n`;
  });
  
  text += `\nGenerated by Plagiarism Split Checker`;
  
  return text;
};

export const getShareableURL = (finalPercentage, chunks) => {
  const data = {
    percentage: finalPercentage,
    chunks: chunks.map(c => ({ w: c.wordCount, p: c.plagiarismPercentage })),
    timestamp: Date.now()
  };
  
  const encoded = btoa(JSON.stringify(data));
  return `${window.location.origin}${window.location.pathname}?results=${encoded}`;
};
